Fix native extension compilation with GCC 15
Getting the following error when compiling the gem on a system running
GCC 15:

    /home/gabi/.rubies/ruby-3.3.0/include/ruby-3.3.0/ruby/internal/anyargs.h:308:143: error: passing argument 3 of ‘rb_define_singleton_method_00’ from incompatible pointer type [-Wincompatible-pointer-types]
    308 | #define rb_define_singleton_method(obj, mid, func, arity)   RBIMPL_ANYARGS_DISPATCH_rb_define_singleton_method((arity), (func))((obj), (mid), (func), (arity))
        |                                                                                                                                               ^~~~~~
        |                                                                                                                                               |
        |                                                                                                                                               VALUE (*)(void) {aka long unsigned int (*)(void)}

Fix the issue by adding the function argument even though it's unused.

Fixes #551